// src/views/sections/education.vue
<template>
  <Section>

    <template slot="header">
      <h2>Educations</h2>
      <p></p>
    </template>

    <Card1b year="2015-2017"
            title="Master of Science"
            institution="Nat'l. Taiwan Univ."
            img-src="/img/logo/ntu_logo.png">
      <template><b-link href="http://www.math.ntu.edu.tw/~iams/eng" target="_blank">Institute of Applied Mathematical Sciences</b-link>,<br />National Taiwan University, Taipei, Taiwan</template>
    </Card1b>

    <Card1b year="2011-2015"
            title="Bachelor of Science"
            institution="Nat'l. Taiwan Univ."
            img-src="/img/logo/ntu_logo.png">
      <template><b-link href="http://www.math.ntu.edu.tw/en" target="_blank">Department of Mathematics</b-link>,<br />National Taiwan University, Taipei, Taiwan</template>
    </Card1b>

  </Section>
</template>

<script>
import Section from './_section.vue';
import Card1b from '@/components/card1b.vue';

export default {
  name: 'Education',
  components: {
    Section,
    Card1b,
  },
};
</script>

// src/pages/sections/Education.tsx
import React from 'react';

import { CardA2 } from '../../components/cards/CardA';
import { Section, SectionElement, SectionProps } from './Section';

////////////////////////////////////////////////////////////////////////////////

export type EducationProps = Omit<SectionProps, 'header' | 'children'>;

export const Education = React.forwardRef(function Education(
  props: EducationProps,
  ref: React.ForwardedRef<SectionElement>,
): JSX.Element {
  const header = <h2>Education</h2>;

  const body = (
    <>
      <CardA2
        year="2015-2017"
        title="Master of Science"
        inst="Nat'l. Taiwan Univ."
        imgSrc="/img/logo/ntu_logo.png"
      >
        <a
          href="http://www.math.ntu.edu.tw/~iams/eng"
          target="_blank"
          rel="noreferrer"
        >
          Institute of Applied Mathematical Sciences
        </a>
        ,<br />
        National Taiwan University, Taipei, Taiwan
      </CardA2>

      <CardA2
        year="2011-2015"
        title="Bachelor of Science"
        inst="Nat'l. Taiwan Univ."
        imgSrc="/img/logo/ntu_logo.png"
      >
        <a
          href="http://www.math.ntu.edu.tw/en"
          target="_blank"
          rel="noreferrer"
        >
          Department of Mathematics
        </a>
        ,<br />
        National Taiwan University, Taipei, Taiwan
      </CardA2>
    </>
  );

  return (
    <Section {...props} ref={ref} header={header}>
      {body}
    </Section>
  );
});
